-- ====================================================
-- Script SQL para criação de tabelas e inserts iniciais
-- ====================================================

-- 1. Criação da tabela ITEM_CARDAPIO
CREATE TABLE item_cardapio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(500),
    preco NUMBER(10,2) NOT NULL,
    categoria VARCHAR2(50),
    disponivel NUMBER(1) DEFAULT 1,
    imagem_url VARCHAR2(500)
);

-- 2. Criação da tabela PEDIDO
CREATE TABLE pedido (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comanda NUMBER NOT NULL,
    id_item NUMBER NOT NULL,
    quantidade NUMBER(5) NOT NULL,
    status VARCHAR2(50),
    observacao VARCHAR2(500),
    data_hora TIMESTAMP,
    CONSTRAINT fk_item FOREIGN KEY (id_item)
        REFERENCES item_cardapio(id)
);

-- ====================================================
-- Inserts iniciais para ITEM_CARDAPIO
-- ====================================================
INSERT INTO item_cardapio (nome, descricao, preco, categoria, disponivel, imagem_url)
VALUES ('Pizza Calabresa', 'Deliciosa pizza com calabresa', 35.00, 'PRATO', 1, NULL);

INSERT INTO item_cardapio (nome, descricao, preco, categoria, disponivel, imagem_url)
VALUES ('Refrigerante', 'Coca Cola 350ml', 8.50, 'BEBIDA', 1, NULL);

INSERT INTO item_cardapio (nome, descricao, preco, categoria, disponivel, imagem_url)
VALUES ('Sorvete Chocolate', 'Sobremesa gelada', 12.00, 'SOBREMESA', 1, NULL);

-- ====================================================
-- Inserts iniciais para PEDIDO
-- ====================================================
-- Assumindo que os IDs de item_cardapio gerados sejam 1, 2 e 3
INSERT INTO pedido (id_comanda, id_item, quantidade, status, observacao, data_hora)
VALUES (1001, 1, 1, 'EM_PREPARO', 'Sem queijo ralado', SYSTIMESTAMP);

INSERT INTO pedido (id_comanda, id_item, quantidade, status, observacao, data_hora)
VALUES (1001, 2, 2, 'EM_PREPARO', 'Um com gelo, outro sem', SYSTIMESTAMP);

INSERT INTO pedido (id_comanda, id_item, quantidade, status, observacao, data_hora)
VALUES (1002, 3, 1, 'ENTREGUE', 'Entrega prioridade', SYSTIMESTAMP - INTERVAL '2' HOUR);
