-- ====================================================
-- 🍽️ SCRIPT SQL - Criação de Tabelas e Dados Iniciais
-- ====================================================

-- 1️⃣ Tabela ITEM_CARDAPIO
CREATE TABLE item_cardapio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(500),
    preco NUMBER(10,2) NOT NULL,
    categoria VARCHAR2(50),
    disponivel NUMBER(1) DEFAULT 1,
    imagem_url VARCHAR2(500)
);

-- 2️⃣ Tabela PEDIDO
CREATE TABLE pedido (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comanda NUMBER NOT NULL,
    status VARCHAR2(50) DEFAULT 'EM_PREPARO',
    observacao VARCHAR2(500),
    data_hora TIMESTAMP DEFAULT SYSTIMESTAMP,
    total NUMBER(12,2) DEFAULT 0
);

-- 3️⃣ Tabela PEDIDO_ITEM (relação N:N entre Pedido e ItemCardapio)
CREATE TABLE pedido_item (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id NUMBER NOT NULL,
    item_cardapio_id NUMBER NOT NULL,
    quantidade NUMBER(5) NOT NULL,
    preco_unitario NUMBER(10,2) NOT NULL,
    subtotal NUMBER(12,2) NOT NULL,
    CONSTRAINT fk_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id) ON DELETE CASCADE,
    CONSTRAINT fk_item FOREIGN KEY (item_cardapio_id) REFERENCES item_cardapio(id)
);

-- ====================================================
-- 🍕 Inserts iniciais - ITEM_CARDAPIO
-- ====================================================
INSERT INTO item_cardapio (nome, descricao, preco, categoria, disponivel, imagem_url)
VALUES ('Pizza Calabresa', 'Deliciosa pizza com calabresa', 35.00, 'PRATO', 1, NULL);

INSERT INTO item_cardapio (nome, descricao, preco, categoria, disponivel, imagem_url)
VALUES ('Refrigerante', 'Coca Cola 350ml', 8.50, 'BEBIDA', 1, NULL);

INSERT INTO item_cardapio (nome, descricao, preco, categoria, disponivel, imagem_url)
VALUES ('Sorvete Chocolate', 'Sobremesa gelada', 12.00, 'SOBREMESA', 1, NULL);

-- ====================================================
-- 🧾 Inserts iniciais - PEDIDO e PEDIDO_ITEM
-- ====================================================

-- Pedido 1: EM_PREPARO
INSERT INTO pedido (id_comanda, status, observacao, total)
VALUES (1001, 'EM_PREPARO', 'Sem queijo ralado', 35.00);
INSERT INTO pedido_item (pedido_id, item_cardapio_id, quantidade, preco_unitario, subtotal)
VALUES (1, 1, 1, 35.00, 35.00);

-- Pedido 2: PRONTO
INSERT INTO pedido (id_comanda, status, observacao, total)
VALUES (1002, 'PRONTO', 'Um com gelo, outro sem', 17.00);
INSERT INTO pedido_item (pedido_id, item_cardapio_id, quantidade, preco_unitario, subtotal)
VALUES (2, 2, 2, 8.50, 17.00);

-- Pedido 3: ENTREGUE
INSERT INTO pedido (id_comanda, status, observacao, total)
VALUES (1003, 'ENTREGUE', 'Entrega prioridade', 12.00);
INSERT INTO pedido_item (pedido_id, item_cardapio_id, quantidade, preco_unitario, subtotal)
VALUES (3, 3, 1, 12.00, 12.00);

-- Pedido 4: CANCELADO
INSERT INTO pedido (id_comanda, status, observacao, total)
VALUES (1004, 'CANCELADO', 'Cliente desistiu do pedido', 0.00);
